### ISSUE TITLE
Поиск вакансий по отраслям

### ISSUE THREAD

**Issue by ehles** [ac-dc/superjob-api-client#1]
Добрый день!
Не нашел способа задать вопрос по API кроме как тут.

У всех вакансий (у всех ли?) есть указание отрасли, есть ли возможность производить поиск вакансий по определённым отраслям?
Есить ли возможность получить через API список всех отраслей?

P.S. под отраслями понимаю вот это:
- catalogues
- array
- Список категорий и отраслей вакансии. Каждый элемент массива есть объект, который содержит ID в ключе id и название каталога в ключе 'title'. Кроме того, если есть ключ 'thread' - это категория, а если нет - то отрасль. В ключе 'thread' находится точно такой же по структуре объект - отрасль.

**Comment by ac-dc** [comment]
Указание отрасли есть у всех вакансий;
Поиск можно производить по отраслям, например:
https://api.superjob.ru/1.0/vacancies/?catalogues=34,175,329

Список отраслей есть пока только в виде XML
http://www.superjob.ru/export/settings/catalog.xml

**Comment by ac-dc** [comment]
Реализованы методы API для работы с отраслями и разделами каталога:
https://api.superjob.ru/1.0/catalogues/
https://api.superjob.ru/1.0/catalogues/parent/33
https://api.superjob.ru/1.0/catalogues/34

**Comment by ehles** [comment]
Отлично! Спасибо большое!!!
