### ISSUE TITLE
Поиск вакансий по параметрам

### ISSUE THREAD

**Issue by ehles** [ac-dc/superjob-api-client#2]
День добрый,
- Запрос вакансии с окладом
  https://api.superjob.ru/1.0/vacancies/?payment_from=15000
  в результатах есть ваканси с нулевым окладом, например id 26427921, 26427917.
- запрос вакансий с водит. правами
  https://api.superjob.ru/1.0/vacancies/?driving_licence[]=A
  в результатах есть вакансии без указания водительских прав, например: 12349904, 26427921
- запрос вакансий от агенств:
  https://api.superjob.ru/1.0/vacancies/?agency=1
  выдает вакансии от работодателей, например vacancy id : 26339713
- Параметр education, тоже выдает результаты с нулевыми значениями.
  https://api.superjob.ru/1.0/vacancies/?education=2

это так и задумано или я делаю что-то не правильно?
Спасибо!

**Comment by ac-dc** [comment]
1. Нулевой оклад означает "по договорённости" и по умолчанию выводится. Чтобы не выводился, установите no_agreement=1, например: https://api.superjob.ru/1.0/vacancies/?payment_from=15000&no_agreement=1
2. Чтобы наличие прав имело значение, установите флаг driving_particular=1, например:  https://api.superjob.ru/1.0/vacancies/?driving_licence%5B%5D=A&driving_particular=1
3. У нас была ошибка в документации, чтобы получить вакансии агентств, используйте параметр agency=2 
   https://api.superjob.ru/1.0/vacancies/?agency=2
4. Образование так же выдаётся с нулевыми значениями, что значит "образование не имеет значения в вакансии".

**Comment by ehles** [comment]
Спасибо большое за пояснения, ещё хотелось бы уточнить по поводу образования, получаестся никак нельзя получить только вакансии где требуются люди с только высшым образованием?

**Comment by ac-dc** [comment]
Пока нет, потому что не было пока в таком фильтре потребности.

**Comment by ehles** [comment]
Ок, ещё раз спасибо!
